set(lvgl_srcs
    src/core/lv_disp.c
    src/core/lv_disp.h
    src/core/lv_event.c
    src/core/lv_event.h
    src/core/lv_group.c
    src/core/lv_group.h
    src/core/lv_indev.c
    src/core/lv_indev.h
    src/core/lv_indev_scroll.c
    src/core/lv_indev_scroll.h
    src/core/lv_obj.c
    src/core/lv_obj.h
    src/core/lv_obj_class.c
    src/core/lv_obj_class.h
    src/core/lv_obj_draw.c
    src/core/lv_obj_draw.h
    src/core/lv_obj_pos.c
    src/core/lv_obj_pos.h
    src/core/lv_obj_scroll.c
    src/core/lv_obj_scroll.h
    src/core/lv_obj_style.c
    src/core/lv_obj_style.h
    src/core/lv_obj_style_gen.c
    src/core/lv_obj_style_gen.h
    src/core/lv_obj_tree.c
    src/core/lv_obj_tree.h
    src/core/lv_refr.c
    src/core/lv_refr.h
    src/core/lv_theme.c
    src/core/lv_theme.h
    src/draw/lv_draw.c
    src/draw/lv_draw.h
    src/draw/lv_draw_arc.c
    src/draw/lv_draw_arc.h
    src/draw/lv_draw_blend.c
    src/draw/lv_draw_blend.h
    src/draw/lv_draw_img.c
    src/draw/lv_draw_img.h
    src/draw/lv_draw_label.c
    src/draw/lv_draw_label.h
    src/draw/lv_draw_line.c
    src/draw/lv_draw_line.h
    src/draw/lv_draw_mask.h
    src/draw/lv_draw_rect.c
    src/draw/lv_draw_rect.h
    src/draw/lv_draw_triangle.c
    src/draw/lv_draw_triangle.h
    src/draw/lv_img_buf.c
    src/draw/lv_img_buf.h
    src/draw/lv_img_cache.c
    src/draw/lv_img_cache.h
    src/draw/lv_img_decoder.c
    src/draw/lv_img_decoder.h
    src/draw/sw/lv_draw_sw.c
    src/draw/sw/lv_draw_sw.h
    src/draw/sw/lv_draw_sw_arc.c
    src/draw/sw/lv_draw_sw_blend.c
    src/draw/sw/lv_draw_sw_img.c
    src/draw/sw/lv_draw_sw_letter.c
    src/draw/sw/lv_draw_sw_line.c
    src/draw/sw/lv_draw_sw_mask.c
    src/draw/sw/lv_draw_sw_polygon.c
    src/draw/sw/lv_draw_sw_rect.c
    src/extra/layouts/flex/lv_flex.c
    src/extra/layouts/flex/lv_flex.h
    src/extra/layouts/grid/lv_grid.c
    src/extra/layouts/grid/lv_grid.h
    src/extra/layouts/lv_layouts.h
    src/extra/libs/bmp/lv_bmp.c
    src/extra/libs/bmp/lv_bmp.h
    src/extra/libs/ffmpeg/lv_ffmpeg.c
    src/extra/libs/ffmpeg/lv_ffmpeg.h
    src/extra/libs/freetype/arial.ttf
    src/extra/libs/freetype/lv_freetype.c
    src/extra/libs/freetype/lv_freetype.h
    src/extra/libs/fsdrv/lv_fsdrv.h
    src/extra/libs/fsdrv/lv_fs_fatfs.c
    src/extra/libs/fsdrv/lv_fs_posix.c
    src/extra/libs/fsdrv/lv_fs_stdio.c
    src/extra/libs/fsdrv/lv_fs_win32.c
    src/extra/libs/gif/gifdec.c
    src/extra/libs/gif/gifdec.h
    src/extra/libs/gif/lv_gif.c
    src/extra/libs/gif/lv_gif.h
    src/extra/libs/lv_libs.h
    src/extra/libs/png/lodepng.c
    src/extra/libs/png/lodepng.h
    src/extra/libs/png/lv_png.c
    src/extra/libs/png/lv_png.h
    src/extra/libs/qrcode/lv_qrcode.c
    src/extra/libs/qrcode/lv_qrcode.h
    src/extra/libs/qrcode/qrcodegen.c
    src/extra/libs/qrcode/qrcodegen.h
    src/extra/libs/rlottie/lv_rlottie.c
    src/extra/libs/rlottie/lv_rlottie.h
    src/extra/libs/sjpg/lv_sjpg.c
    src/extra/libs/sjpg/lv_sjpg.h
    src/extra/libs/sjpg/tjpgd.c
    src/extra/libs/sjpg/tjpgd.h
    src/extra/libs/sjpg/tjpgdcnf.h
    src/extra/lv_extra.c
    src/extra/lv_extra.h
    src/extra/others/lv_others.h
    src/extra/others/snapshot/lv_snapshot.c
    src/extra/others/snapshot/lv_snapshot.h
    src/extra/README.md
    src/extra/themes/basic/lv_theme_basic.c
    src/extra/themes/basic/lv_theme_basic.h
    src/extra/themes/default/lv_theme_default.c
    src/extra/themes/default/lv_theme_default.h
    src/extra/themes/lv_themes.h
    src/extra/themes/mono/lv_theme_mono.c
    src/extra/themes/mono/lv_theme_mono.h
    src/extra/widgets/animimg/lv_animimg.c
    src/extra/widgets/animimg/lv_animimg.h
    src/extra/widgets/calendar/lv_calendar.c
    src/extra/widgets/calendar/lv_calendar.h
    src/extra/widgets/calendar/lv_calendar_header_arrow.c
    src/extra/widgets/calendar/lv_calendar_header_arrow.h
    src/extra/widgets/calendar/lv_calendar_header_dropdown.c
    src/extra/widgets/calendar/lv_calendar_header_dropdown.h
    src/extra/widgets/chart/lv_chart.c
    src/extra/widgets/chart/lv_chart.h
    src/extra/widgets/colorwheel/lv_colorwheel.c
    src/extra/widgets/colorwheel/lv_colorwheel.h
    src/extra/widgets/imgbtn/lv_imgbtn.c
    src/extra/widgets/imgbtn/lv_imgbtn.h
    src/extra/widgets/keyboard/lv_keyboard.c
    src/extra/widgets/keyboard/lv_keyboard.h
    src/extra/widgets/led/lv_led.c
    src/extra/widgets/led/lv_led.h
    src/extra/widgets/list/lv_list.c
    src/extra/widgets/list/lv_list.h
    src/extra/widgets/lv_widgets.h
    src/extra/widgets/menu/lv_menu.c
    src/extra/widgets/menu/lv_menu.h
    src/extra/widgets/meter/lv_meter.c
    src/extra/widgets/meter/lv_meter.h
    src/extra/widgets/msgbox/lv_msgbox.c
    src/extra/widgets/msgbox/lv_msgbox.h
    src/extra/widgets/span/lv_span.c
    src/extra/widgets/span/lv_span.h
    src/extra/widgets/spinbox/lv_spinbox.c
    src/extra/widgets/spinbox/lv_spinbox.h
    src/extra/widgets/spinner/lv_spinner.c
    src/extra/widgets/spinner/lv_spinner.h
    src/extra/widgets/tabview/lv_tabview.c
    src/extra/widgets/tabview/lv_tabview.h
    src/extra/widgets/tileview/lv_tileview.c
    src/extra/widgets/tileview/lv_tileview.h
    src/extra/widgets/win/lv_win.c
    src/extra/widgets/win/lv_win.h
    src/font/lv_font.c
    src/font/lv_font.h
    src/font/lv_font_dejavu_16_persian_hebrew.c
    src/font/lv_font_fmt_txt.c
    src/font/lv_font_fmt_txt.h
    src/font/lv_font_loader.c
    src/font/lv_font_loader.h
    src/font/lv_font_montserrat_10.c
    src/font/lv_font_montserrat_12.c
    src/font/lv_font_montserrat_12_subpx.c
    src/font/lv_font_montserrat_14.c
    src/font/lv_font_montserrat_16.c
    src/font/lv_font_montserrat_18.c
    src/font/lv_font_montserrat_20.c
    src/font/lv_font_montserrat_22.c
    src/font/lv_font_montserrat_24.c
    src/font/lv_font_montserrat_26.c
    src/font/lv_font_montserrat_28.c
    src/font/lv_font_montserrat_28_compressed.c
    src/font/lv_font_montserrat_30.c
    src/font/lv_font_montserrat_32.c
    src/font/lv_font_montserrat_34.c
    src/font/lv_font_montserrat_36.c
    src/font/lv_font_montserrat_38.c
    src/font/lv_font_montserrat_40.c
    src/font/lv_font_montserrat_42.c
    src/font/lv_font_montserrat_44.c
    src/font/lv_font_montserrat_46.c
    src/font/lv_font_montserrat_48.c
    src/font/lv_font_montserrat_8.c
    src/font/lv_font_simsun_16_cjk.c
    src/font/lv_font_unscii_16.c
    src/font/lv_font_unscii_8.c
    src/font/lv_symbol_def.h
    src/hal/lv_hal.h
    src/hal/lv_hal_disp.c
    src/hal/lv_hal_disp.h
    src/hal/lv_hal_indev.c
    src/hal/lv_hal_indev.h
    src/hal/lv_hal_tick.c
    src/hal/lv_hal_tick.h
    src/lvgl.h
    src/lv_api_map.h
    src/lv_conf_internal.h
    src/lv_conf_kconfig.h
    src/misc/lv_anim.c
    src/misc/lv_anim.h
    src/misc/lv_anim_timeline.c
    src/misc/lv_anim_timeline.h
    src/misc/lv_area.c
    src/misc/lv_area.h
    src/misc/lv_assert.h
    src/misc/lv_async.c
    src/misc/lv_async.h
    src/misc/lv_bidi.c
    src/misc/lv_bidi.h
    src/misc/lv_color.c
    src/misc/lv_color.h
    src/misc/lv_fs.c
    src/misc/lv_fs.h
    src/misc/lv_gc.c
    src/misc/lv_gc.h
    src/misc/lv_ll.c
    src/misc/lv_ll.h
    src/misc/lv_log.c
    src/misc/lv_log.h
    src/misc/lv_math.c
    src/misc/lv_math.h
    src/misc/lv_mem.c
    src/misc/lv_mem.h
    src/misc/lv_printf.c
    src/misc/lv_printf.h
    src/misc/lv_style.c
    src/misc/lv_style.h
    src/misc/lv_style_gen.c
    src/misc/lv_style_gen.h
    src/misc/lv_templ.c
    src/misc/lv_templ.h
    src/misc/lv_timer.c
    src/misc/lv_timer.h
    src/misc/lv_tlsf.c
    src/misc/lv_tlsf.h
    src/misc/lv_txt.c
    src/misc/lv_txt.h
    src/misc/lv_txt_ap.c
    src/misc/lv_txt_ap.h
    src/misc/lv_types.h
    src/misc/lv_utils.c
    src/misc/lv_utils.h
    src/widgets/lv_arc.c
    src/widgets/lv_arc.h
    src/widgets/lv_bar.c
    src/widgets/lv_bar.h
    src/widgets/lv_btn.c
    src/widgets/lv_btn.h
    src/widgets/lv_btnmatrix.c
    src/widgets/lv_btnmatrix.h
    src/widgets/lv_canvas.c
    src/widgets/lv_canvas.h
    src/widgets/lv_checkbox.c
    src/widgets/lv_checkbox.h
    src/widgets/lv_dropdown.c
    src/widgets/lv_dropdown.h
    src/widgets/lv_img.c
    src/widgets/lv_img.h
    src/widgets/lv_label.c
    src/widgets/lv_label.h
    src/widgets/lv_line.c
    src/widgets/lv_line.h
    src/widgets/lv_objx_templ.c
    src/widgets/lv_objx_templ.h
    src/widgets/lv_roller.c
    src/widgets/lv_roller.h
    src/widgets/lv_slider.c
    src/widgets/lv_slider.h
    src/widgets/lv_switch.c
    src/widgets/lv_switch.h
    src/widgets/lv_table.c
    src/widgets/lv_table.h
    src/widgets/lv_textarea.c
    src/widgets/lv_textarea.h
    )
